### ISSUE TITLE
[Question] Where is the Ingress or how is it generated from Skaffold?

### ISSUE THREAD

**Issue by scheung38** [uzi0espil/cookiecutter-django-k8s#19]
I see you have kubernetes/ingress folder but inside it is not using kind: Ingress but Loadbalancer?

if we are using Skaffold do we need to manually create Ingress or it is automatically generated from the production.yml file?

**Comment by uzi0espil** [comment]
In my case, since I have few access points for which the ingresses are not frequently changed, then I have opted to create Traefik as Deployment and not as an Ingress controller and passed the Traefik options through configmap. Therefore, Traefik will be created from production.yml. The ingress folder only host the LoadBalancer Service for the traefik controller.

For further information about Ingress for this project, you can find it in this article I wrote when developed this repo: https://medium.com/compredict/hands-on-day-1-and-day-2-operations-in-kubernetes-using-django-and-aks-part-3-1bf09984b6ee

**Comment by uzi0espil** [comment]
I will close the issue, please feel free to re-open if you need further verifications.

**Comment by scheung38** [comment]
When you say 'few' does that mean many or not many?

**Comment by uzi0espil** [comment]
not many at all, in Django Cookiecutter, you only have two endpoints:

- Django endpoint.
- Flower endpoint. (should be only for internal purposes)

Since there are only two, it would be simpler to go with configfile approach over setting up Traefik as Ingress Controller.

**Comment by scheung38** [comment]
@uzi0espil 

Why was this commented out ?

line 5 of compose/production/traefik/Dockerfile

COPY ./compose/production/traefik/traefik.yml /etc/traefik
